### ISSUE TITLE
android report an error

### ISSUE THREAD

**Issue by coderafei** [magicismight/react-native-advanced-webview#29]
uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [editor:react-native-advanced-webview:unspecified] /Users/afei/Codes/test/editor/android/app/build/intermediates/exploded-aar/editor/react-native-advanced-webview/unspecified/AndroidManifest.xml
        Suggestion: use tools:overrideLibrary="im.shimo.react.webview" to force usage

**Comment by coderafei** [comment]
change
minSdkVersion 19
resolve this

**Comment by greedbell** [comment]
fixed by #30

**Comment by coderafei** [comment]
@greedbell 👍 
顺便问一下，石墨也是用的这个增强webview吗？

**Comment by greedbell** [comment]
@coderafei YES
